// AUTO-GENERATED by scripts/generate-frontend-config.js — do not edit by hand.
// Re-run with: node scripts/generate-frontend-config.js
window.SCALES_CONFIG = {
  "API_BASE": "https://0f223nfaq2.execute-api.us-east-1.amazonaws.com"
};
